#!/bin/bash

SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
have_real=$(type -p realpath)
[ "${have_real}" ] && SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

cd "${SCRIPT_PATH}"

[ -f VERSION ] || {
  echo "ERROR: missing VERSION file"
  exit 1
}

. ./VERSION

cd ..

tar cf - mcp/bin \
         mcp/doc \
         mcp/env* \
         mcp/etc/nginx/sites-available \
         mcp/etc/*.service \
         mcp/install \
         mcp/models \
         mcp/scripts \
         mcp/PORTS \
         mcp/VERSION \
         mcp/tests \
         mcp/sbin | gzip -9 > mcp/mcp-${VERSION}-${RELEASE}.tar.gz
