#!/bin/bash

SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
have_real=$(type -p realpath)
[ "${have_real}" ] && SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

cd "${SCRIPT_PATH}"

[ -f VERSION ] || {
  echo "ERROR: missing VERSION file"
  exit 1
}

. ./VERSION

cd ..

tar cf - llm/bin \
         llm/doc \
         llm/env* \
         llm/etc/nginx/sites-available \
         llm/etc/*.service \
         llm/install \
         llm/models \
         llm/scripts \
         llm/PORTS \
         llm/VERSION \
         llm/tests \
         llm/sbin | gzip -9 > llm/llm-${VERSION}-${RELEASE}.tar.gz
