#!/bin/bash

SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
have_real=$(type -p realpath)
[ "${have_real}" ] && SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

cd "${SCRIPT_PATH}"

[ -f VERSION ] || {
    echo "VERSION file missing. Exiting."
    exit 1
}
. ./VERSION

usage() {
    printf "\nUsage: mkrelease [-d] [-u]"
    printf "\nWhere:"
    printf "\n\t-d indicates create draft release"
    printf "\n\t-u displays this usage message and exits\n"
    exit 1
}

DRAFT=
while getopts "du" flag; do
    case $flag in
        d)
            DRAFT="--draft"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

export PATH="$HOME/.local/bin:${PATH}"

if [ -f ${HOME}/.mrprivate ]; then
  source ${HOME}/.mrprivate
else
  echo "ERROR: Could not locate ${HOME}/.mrprivate"
  exit 1
fi

[ -x ./mkdist ] || {
  echo "ERROR: missing mkdist"
  exit 1
}
./mkdist

[ -f llm-${VERSION}-${RELEASE}.tar.gz ] || {
  echo "ERROR: missing llm-${VERSION}-${RELEASE}.tar.gz"
  exit 1
}

ANNO="Open WebUI setup with Ollama and vLLM, version v${VERSION}r${RELEASE}"
gittag v${VERSION}r${RELEASE} ${ANNO}

echo "Creating release for version ${VERSION} release ${RELEASE}"

gh release create v${VERSION}r${RELEASE} ${DRAFT} \
                  --title "${ANNO}" \
                  --target "${BRANCH}" \
                  --notes-file ReleaseNotes.md \
                  install \
                  llm-${VERSION}-${RELEASE}.tar.gz

git fetch --tags origin

rm -f llm-${VERSION}-${RELEASE}.tar.gz
