#!/bin/bash

PYENV_ROOT="/mnt/llm/.venv"
export PATH="${PYENV_ROOT}/bin:${PATH}"

[ "${HOST}" ] || HOST=127.0.0.1
[ "${PORT}" ] || PORT=6000

source ${PYENV_ROOT}/bin/activate

have_web=$(type -p open-webui)
if [ "${have_web}" ]; then
  open-webui serve --host ${HOST} --port ${PORT}
else
  echo "ERROR: cannot locate open-webui command"
fi
